import type { JobPin } from "@/types/job";

/** 서울 시청 인근 데모 좌표 — 이후 Supabase `job_postings` 로 교체 */
export const MOCK_JOBS: JobPin[] = [
  {
    id: "1",
    title: "편의점 야간 스태프",
    company: "행복마트 종로점",
    wageLabel: "시급 12,000원",
    address: "서울 종로구 세종대로 1",
    lat: 37.56635,
    lng: 126.97797,
    category: "생활 서비스",
    trust: { businessVerified: true, identityVerified: true },
  },
  {
    id: "2",
    title: "아파트 경비 (주간)",
    company: "한강힐스 관리단",
    wageLabel: "월 180만원",
    address: "서울 중구 을지로 12",
    lat: 37.5658,
    lng: 126.9825,
    category: "생활 서비스",
    trust: { businessVerified: false, identityVerified: true },
  },
  {
    id: "3",
    title: "시험 감독 보조",
    company: "서울시 교육청 대행",
    wageLabel: "일당 9만원",
    address: "서울 종로구 혜화동",
    lat: 37.5882,
    lng: 126.996,
    category: "전문/교육",
    trust: { businessVerified: true, identityVerified: false },
  },
  {
    id: "4",
    title: "등하교 안전 도우미",
    company: "샘물초등학교",
    wageLabel: "시급 11,500원",
    address: "서울 종로구 평창동",
    lat: 37.612,
    lng: 126.97,
    category: "공공/돌봄",
  },
  {
    id: "5",
    title: "AI 학습 데이터 라벨링",
    company: "테크파트너스",
    wageLabel: "건당 800원",
    address: "서울 중구 을지로 7가",
    lat: 37.5668,
    lng: 126.991,
    category: "디지털/신규",
  },
  {
    id: "6",
    title: "전시 도슨트 (주말)",
    company: "국립민속박물관",
    wageLabel: "시급 13,000원",
    address: "서울 종로구 삼청로",
    lat: 37.5796,
    lng: 126.977,
    category: "전문/교육",
  },
  {
    id: "7",
    title: "주차장 요금 정산",
    company: "시청 공영주차장",
    wageLabel: "시급 10,500원",
    address: "서울 중구 세종대로 110",
    lat: 37.5636,
    lng: 126.9754,
    category: "생활 서비스",
  },
  {
    id: "8",
    title: "시니어 카페 매장 보조",
    company: "느린걸음 카페",
    wageLabel: "시급 11,000원",
    address: "서울 종로구 인사동",
    lat: 37.5714,
    lng: 126.986,
    category: "공공/돌봄",
  },
];
